version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: stock_visualizer_image_flask
    container_name: stock_visualizer_container_flask
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"